#!/usr/bin/env python3
import sys
import random

def gen():
    for i in range(int(sys.argv[1])):
        print("A ",end= "")
        print(random.randint(0,1920), end= " ")
        print(random.randint(0,1080), end= " ")
        print(random.randint(0,1920), end= " ")
        print(random.randint(0,1080), end= " ")
        print(random.randint(1,50), end= " ")
        print("0")
gen()